package home.control.java;

public class HomeControlJava extends javax.swing.JFrame {

  public HomeControlJava() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    proj_pwr_off_btn = new javax.swing.JButton();
    proj_pwr_on_btn = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    statusLabel = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    atv_up_btn = new javax.swing.JButton();
    atv_left_btn = new javax.swing.JButton();
    atv_right_btn = new javax.swing.JButton();
    atv_down_btn = new javax.swing.JButton();
    atv_center_btn = new javax.swing.JButton();
    atv_menu_btn = new javax.swing.JButton();
    atv_play_btn = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Home Control");

    proj_pwr_off_btn.setText("Power Off");
    proj_pwr_off_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        proj_pwr_off_btnActionPerformed(evt);
      }
    });

    proj_pwr_on_btn.setText("Power On");
    proj_pwr_on_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        proj_pwr_on_btnActionPerformed(evt);
      }
    });

    jLabel2.setText("Projector");

    jLabel3.setText("Status:");

    jLabel4.setText("Apple TV");

    atv_up_btn.setText("Up");
    atv_up_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atv_up_btnActionPerformed(evt);
      }
    });

    atv_left_btn.setText("Left");
    atv_left_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atv_left_btnActionPerformed(evt);
      }
    });

    atv_right_btn.setText("Right");
    atv_right_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atv_right_btnActionPerformed(evt);
      }
    });

    atv_down_btn.setText("Down");
    atv_down_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atv_down_btnActionPerformed(evt);
      }
    });

    atv_center_btn.setText("Center");
    atv_center_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atv_center_btnActionPerformed(evt);
      }
    });

    atv_menu_btn.setText("Menu");
    atv_menu_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atv_menu_btnActionPerformed(evt);
      }
    });

    atv_play_btn.setText("Play/Pause");
    atv_play_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atv_play_btnActionPerformed(evt);
      }
    });

    jLabel5.setText("Receiver");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(51, 51, 51)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(statusLabel)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1))
              .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(proj_pwr_off_btn)
                .addComponent(proj_pwr_on_btn))
              .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(97, 97, 97))
              .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(atv_play_btn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atv_menu_btn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(atv_left_btn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(atv_down_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(atv_up_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(atv_center_btn))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atv_right_btn)))))))
        .addGap(14, 14, 14))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proj_pwr_on_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proj_pwr_off_btn))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atv_up_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(atv_left_btn)
                  .addComponent(atv_right_btn)
                  .addComponent(atv_center_btn))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(atv_down_btn)
            .addGap(6, 6, 6))
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(atv_menu_btn)
          .addComponent(atv_play_btn))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(statusLabel))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void proj_pwr_on_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proj_pwr_on_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.200", 8899, "\r*pow=on#\r"));
  }//GEN-LAST:event_proj_pwr_on_btnActionPerformed

  private void proj_pwr_off_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proj_pwr_off_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.200", 8899, "\r*pow=off#\r"));
  }//GEN-LAST:event_proj_pwr_off_btnActionPerformed

  private void atv_up_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atv_up_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.201", 4998, "\rsendir,1:2,1,38580,1,1,348,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,65,21,65,21,22,21,65,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,1559,347,87,21,4938\r"));
  }//GEN-LAST:event_atv_up_btnActionPerformed

  private void atv_left_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atv_left_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.201", 4998, "\rsendir,1:2,1,38580,1,1,348,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,1645,347,87,21,4938\r"));
  }//GEN-LAST:event_atv_left_btnActionPerformed

  private void atv_center_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atv_center_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.201", 4998, "\rsendir,1:2,1,38580,1,1,348,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,65,21,22,21,65,21,65,21,65,21,22,21,65,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,1479,347,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,65,21,22,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,4938\r"));
  }//GEN-LAST:event_atv_center_btnActionPerformed

  private void atv_right_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atv_right_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.201", 4998, "\rsendir,1:2,1,38580,1,1,348,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,1558,347,87,21,4938\r"));
  }//GEN-LAST:event_atv_right_btnActionPerformed

  private void atv_down_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atv_down_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.201", 4998, "\rsendir,1:2,2,38580,1,1,347,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,65,21,22,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,4938\r"));
  }//GEN-LAST:event_atv_down_btnActionPerformed

  private void atv_play_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atv_play_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.201", 4998, "\rsendir,1:2,2,38580,1,1,348,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,22,21,65,21,65,21,65,21,65,21,22,21,65,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,1480,347,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,65,21,22,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,4938\r"));
  }//GEN-LAST:event_atv_play_btnActionPerformed

  private void atv_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atv_menu_btnActionPerformed
    statusLabel.setText(Command.sendCommand("10.41.92.201", 4998, "\rsendir,1:2,1,38580,1,1,348,173,21,22,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,65,21,22,21,22,21,22,21,22,21,65,21,22,21,65,21,22,21,22,21,22,21,22,21,22,21,22,21,65,21,22,21,22,21,22,21,65,21,22,21,22,21,23,21,1647,347,87,21,4938\r"));
  }//GEN-LAST:event_atv_menu_btnActionPerformed
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(HomeControlJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(HomeControlJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(HomeControlJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(HomeControlJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>
    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new HomeControlJava().setVisible(true);
      }
    });
    
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton atv_center_btn;
  private javax.swing.JButton atv_down_btn;
  private javax.swing.JButton atv_left_btn;
  private javax.swing.JButton atv_menu_btn;
  private javax.swing.JButton atv_play_btn;
  private javax.swing.JButton atv_right_btn;
  private javax.swing.JButton atv_up_btn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JButton proj_pwr_off_btn;
  private javax.swing.JButton proj_pwr_on_btn;
  private javax.swing.JLabel statusLabel;
  // End of variables declaration//GEN-END:variables
}
